### ISSUE TITLE
Add Cargo.lock to repository

### ISSUE THREAD

**Issue by jirutka** [keszybz/add-determinism#4]
This is needed for reproducible builds… ;)

**Comment by keszybz** [comment]
Nah, Cargo.lock is a misunderstanding, or in other words, a bad solution for a misunderstood problem.

The dependencies are listed using semver, and it is always expected that the program will work with any version of the dependencies that satisfies the bounds. That is all that is needed: always use some recent version of the dependencies. Either the latest, or possibly a few versions back if more stability is desired. But in any case, the dependencies should keep being updated, even if the project using them is not being updated, either because there is nothing to change, or the maintainer is away atm.

Cargo.lock would record the fact I used foo-1.5.7 two months ago, when I last touched the package, and now the latest version is foo-1.7.8. There is no reason whatsoever to use those stale versions of dependencies. They are not in any way "better". They are just some random versions them happened to be latest when I happened to update the dependency tree on my machine.

Also, many projects become stable and don't see constant development. This is very common for stuff like this particular tool. It's likely that after the initial flurry of development, there will be months without any commits. Without Cargo.lock this is not a problem: the compiler and the dependencies keep getting updated, possibly with various bugs fixed on the way, so this tool keeps getting better and better, with no action from the maintainers. With Cargo.lock, each passing month just means the code is getting stale.

The only case where locking to specific versions is useful is when the dependencies are crap. If maintainers of a dependency break compatibility or introduce bugs all the time, *then* the fact that I tested with foo-1.5.7 on machine starts to mean something. But I prefer a different solution: pick dependencies that are not crap. (In particular, pick widely used and well-maintained crates. This is what we do here.)

And finally, "reproducible builds" means different things to different people. But for reproducible builds as defined by reproducible-builds.org, locking down the versions a few dependencies is not enough. The environment, distribution, architecture, variables, would need to be locked down too.

Sorry, but I think Cargo.lock files are fine locally, but should not be committed to git or made part of the public interface.

**Comment by kpcyrd** [comment]
> Without Cargo.lock this is not a problem: the compiler and the dependencies keep getting updated, possibly with various bugs fixed on the way, so this tool keeps getting better and better, with no action from the maintainers.

This is not true in praxis, without a new release the binary is usually not getting rebuilt by distros (potentially for years) and continue to use old and possibly vulnerable dependencies.

It's also not true for local development, each developer is going to have a different combination of dependencies because, unless the `Cargo.toml` is changed in a way the `Cargo.lock` file can't satisfy anymore, the `Cargo.lock` won't get invalidated either and each developer needs to remember to run `cargo update` occasionally. This is one of the reasons Rust now recommends committing the `Cargo.lock` file even for library projects (even though for libraries it won't get used for anything besides CI and development).

> But for reproducible builds as defined by reproducible-builds.org, locking down the versions a few dependencies is not enough. The environment, distribution, architecture, variables, would need to be locked down too.

This is implementation specific, Fedora and Debian both mirror crates.io into their package ecosystem and can rely on their native buildinfo files to record the Rust dependency graph, but Arch Linux, NixOS and Alpine all integrate with crates.io directly and **additionally** need a `Cargo.lock` file to be reproducible (they use either `--locked` or `--frozen`, so the build won't start until a `Cargo.lock` is provided in some way). The resolved Rust dependency graph is considered a "source code input".

This leads to some quirky collaborations, like [Alpine importing Cargo.lock files maintained by Arch Linux](https://git.alpinelinux.org/aports/tree/community/wasm-bindgen/APKBUILD?id=1eff6c5cacddf147fe05a64b8f2632fb401b4df3#n14) to avoid duplicating efforts (which I think is reasonable).

**Comment by keszybz** [comment]
> without a new release the binary is usually not getting rebuilt by distros (potentially for years) and continue to use old and possibly vulnerable dependencies.

Incidentally, the distro that *I* work on, i.e. Fedora, does a mass rebuild every half year, for all packages, even if there is no particular reason to rebuild that particular package. But that's not really the solution. The part that matters is that the distro must rebuild packages *promptly* to fix vulnerabilities and bugs. For dynamically linked compiled binaries and perl/python/java/… it's enough if just the "library" is rebuilt. For statically linked programs, in particular Rust, everything that links the vulnerable code must be rebuilt. Tracking this and updating dependencies and rebuilding everything that needs to be rebuilt is the primary role of the distro.

And `Cargo.lock` certainly wouldn't help with all that, since `Cargo.lock` is about holding back upgrades, not using the latest version.

(And if the package is being rebuilt for some reason, there is no reason not to use the best, i.e. latest, versions of all dependencies.)

> This is implementation specific, Fedora and Debian both mirror crates.io into their package ecosystem and can rely on their native buildinfo files to record the Rust dependency graph, but Arch Linux, NixOS and Alpine all integrate with crates.io directly and **additionally** need a `Cargo.lock` file to be reproducible (they use either `--locked` or `--frozen`, so the build won't start until a `Cargo.lock` is provided in some way). The resolved Rust dependency graph is considered a "source code input"

OK, great, so just generate the `Cargo.lock` file at some point and store it. This `Cargo.lock` file is going to be **better** then the one from upstream, because it's going to be fresher. As I wrote above, I think it's fine to use Cargo.lock "locally", and then the distro can even store this file somewhere if it wants to repeat the builds.

OTOH, sharing `Cargo.lock` between different distros seems … iffy. Alpine is essentially saying "we'll rebuild with those older versions of dependencies because Arch Linux happened to use them". One reason to do that would be if Arch does extensive QA and then those versions is "known good" *and* Alpine is close enough to Arch to assume that those test results carry over. I don't know how much those conditions are satisfied.
